import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:provider/provider.dart';
import 'package:life_rank/features/auth/providers/auth_provider.dart';
import 'package:life_rank/core/constants/app_colors.dart';
import 'package:life_rank/core/constants/wealth_config.dart';
import 'package:life_rank/core/constants/financial_rank_config.dart';
import 'package:life_rank/core/models/category_models.dart';
import 'package:life_rank/core/services/user_stats_service.dart';
import '../widgets/overall_rank_card.dart';
import '../widgets/category_card.dart';
import '../widgets/financial_rank_card.dart';
import '../widgets/financial_metrics_row.dart';
import '../widgets/net_worth_sheet.dart';
import '../widgets/daily_financial_todos.dart';

class DashboardPage extends StatefulWidget {
  const DashboardPage({super.key});

  @override
  State<DashboardPage> createState() => _DashboardPageState();
}

class _DashboardPageState extends State<DashboardPage> {
  List<TransactionModel> _transactions = [];
  CurrencyMode _currencyMode = CurrencyMode.idr;

  /// Manual net worth in IDR — null means use XP-derived value
  double? _manualNetWorthIdr;

  /// Daily financial todos
  List<FinancialTodo> _todos = [];

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _loadInitialData();
    });
  }

  Future<void> _loadInitialData() async {
    final auth = context.read<AuthProvider>();
    if (auth.supabaseUser == null) return;
    final userId = auth.supabaseUser!.id;
    
    final txs = await UserStatsService.getTransactions(userId);
    final nw = await UserStatsService.getLatestNetWorth(userId);
    final td = await UserStatsService.getTodayFinancialTodos(userId);

    if (mounted) {
      setState(() {
        _transactions = txs;
        _manualNetWorthIdr = nw?.amountIdr;
        _todos = td;
      });
    }
  }

  void _toggleCurrency() {
    setState(() {
      _currencyMode =
          _currencyMode == CurrencyMode.idr ? CurrencyMode.usd : CurrencyMode.idr;
    });
  }

  // ── Net Worth CRUD ──────────────────────────────────────────────────────────

  Future<void> _openNetWorthSheet() async {
    final result = await NetWorthSheet.show(
      context,
      currentIdr: _manualNetWorthIdr,
      currencyMode: _currencyMode,
    );
    if (result == null || !mounted) return;

    final auth = context.read<AuthProvider>();
    final userId = auth.supabaseUser?.id;
    if (userId == null) return;

    if (result.isDelete) {
      await UserStatsService.deleteNetWorthEntries(userId);
      setState(() => _manualNetWorthIdr = null);
      _showSnack('Net worth reset ke mode otomatis 🔄');
    } else {
      final mlRank = FinancialRankCalculator.calculate(result.amountIdr).rank;
      await UserStatsService.addNetWorthEntry(
        NetWorthEntry(
          id: '', // Will be generated by DB
          userId: userId,
          amountIdr: result.amountIdr,
          wealthRank: mlRank.displayName,
          recordedAt: DateTime.now(),
        ),
      );
      setState(() => _manualNetWorthIdr = result.amountIdr);
      _showSnack('${mlRank.iconAsset} Net worth updated ke ${mlRank.displayName}!');
    }
  }

  void _showSnack(String msg) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(msg,
            style: const TextStyle(color: AppColors.textPrimary, fontWeight: FontWeight.w600)),
        backgroundColor: AppColors.card,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(16),
        duration: const Duration(seconds: 3),
      ),
    );
  }

  // ── Todo actions ────────────────────────────────────────────────────────────

  Future<void> _completeTodo(FinancialTodo todo) async {
    final auth = context.read<AuthProvider>();
    final userId = auth.supabaseUser?.id;
    if (userId == null) return;

    await UserStatsService.completeFinancialTodo(todo.id);
    await UserStatsService.updateCategoryXp(userId, 'financial', todo.points);
    await auth.refreshStats();

    setState(() {
      final idx = _todos.indexWhere((t) => t.id == todo.id);
      if (idx != -1) _todos[idx].completed = true;
    });
    _showSnack('${todo.icon} +${todo.points} pts — Kerja bagus! 🔥');
  }

  Future<void> _deleteTodo(FinancialTodo todo) async {
    await UserStatsService.deleteFinancialTodo(todo.id);
    setState(() => _todos.removeWhere((t) => t.id == todo.id));
  }

  Future<void> _addCustomTodo(String title) async {
    final auth = context.read<AuthProvider>();
    final userId = auth.supabaseUser?.id;
    if (userId == null) return;

    final newTodo = FinancialTodo(
      id: '', // Generated by DB
      userId: userId,
      title: title,
      desc: '',
      icon: '🎯',
      points: 50,
      isCustom: true,
    );
    
    await UserStatsService.addCustomFinancialTodo(newTodo);
    final updated = await UserStatsService.getTodayFinancialTodos(userId);
    if (mounted) setState(() => _todos = updated);
  }

  @override
  Widget build(BuildContext context) {
    final auth = context.watch<AuthProvider>();
    final stats = auth.stats;
    final profile = auth.profile;

    if (stats == null || profile == null) {
      return const Scaffold(
        backgroundColor: AppColors.background,
        body: Center(
          child: CircularProgressIndicator(color: AppColors.wealthMaster),
        ),
      );
    }

    return Scaffold(
      backgroundColor: AppColors.background,
      // ── FAB: quick edit net worth ──────────────────────────────────────────
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _openNetWorthSheet,
        backgroundColor: AppColors.wealthMaster,
        foregroundColor: Colors.black,
        elevation: 0,
        icon: const Icon(Icons.account_balance_wallet_rounded, size: 20),
        label: const Text(
          'Net Worth',
          style: TextStyle(fontWeight: FontWeight.w800, fontSize: 13, letterSpacing: 0.5),
        ),
      ),
      body: RefreshIndicator(
        onRefresh: () async {
          await auth.refreshStats();
          await _loadInitialData();
        },
        color: AppColors.wealthMaster,
        backgroundColor: AppColors.card,
        child: CustomScrollView(
          slivers: [
            // ── App Bar ────────────────────────────────────────────────────
            SliverAppBar(
              floating: true,
              snap: true,
              backgroundColor: AppColors.background,
              expandedHeight: 56,
              titleSpacing: 20,
              title: Row(
                children: [
                  Container(
                    width: 28,
                    height: 28,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      gradient: const LinearGradient(
                        colors: [AppColors.wealthMaster, AppColors.wealthElite],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: AppColors.wealthMasterGlow,
                          blurRadius: 10,
                          spreadRadius: 1,
                        ),
                      ],
                    ),
                    child: const Center(
                      child: Text('W',
                          style: TextStyle(
                              color: Colors.black,
                              fontSize: 14,
                              fontWeight: FontWeight.w900)),
                    ),
                  ),
                  const SizedBox(width: 10),
                  const Text(
                    'WEALTHRANK',
                    style: TextStyle(
                      color: AppColors.textPrimary,
                      fontSize: 18,
                      fontWeight: FontWeight.w800,
                      letterSpacing: 2.5,
                    ),
                  ),
                ],
              ),
              actions: [
                IconButton(
                  icon: const Icon(Icons.refresh_rounded,
                      color: AppColors.textSecondary, size: 22),
                  onPressed: () async {
                    await auth.refreshStats();
                    await _loadInitialData();
                  },
                ),
                const SizedBox(width: 8),
              ],
            ),

            // ── Main Content ───────────────────────────────────────────────
            SliverPadding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 120),
              sliver: SliverList(
                delegate: SliverChildListDelegate([

                  // ── User Profile Header (Wealth Rank primary) ──────────
                  UserProfileHeader(
                    stats: stats,
                    username: profile.username,
                    currencyMode: _currencyMode,
                    onCurrencyToggle: _toggleCurrency,
                    manualNetWorthIdr: _manualNetWorthIdr,
                    onEditNetWorth: _openNetWorthSheet,
                  ),

                  const SizedBox(height: 20),

                  // ── Net Worth status chip (if manual set) ──────────────
                  if (_manualNetWorthIdr != null)
                    _NetWorthChip(
                      amountIdr: _manualNetWorthIdr!,
                      onEdit: _openNetWorthSheet,
                    ).animate().fadeIn(duration: 300.ms),

                  if (_manualNetWorthIdr != null) const SizedBox(height: 12),

                  // ── Hero Financial Rank Card (ML-style Warrior→Mythic) ─
                  FinancialRankCard(
                    netWorthIdr: _manualNetWorthIdr ??
                        WealthConfig.xpToIdrAmount(stats.financialXp),
                    onTapEdit: _openNetWorthSheet,
                  ),

                  const SizedBox(height: 20),

                  // ── Financial Metrics 2×2 ──────────────────────────────
                  _SectionLabel(
                    label: 'FINANCIAL METRICS',
                    color: AppColors.financial,
                  ).animate().fadeIn(duration: 400.ms, delay: 400.ms),

                  const SizedBox(height: 12),

                  FinancialMetricsRow(
                    transactions: _transactions,
                    currencyMode: _currencyMode,
                  ),

                  const SizedBox(height: 24),

                  // ── Supporting Attributes ──────────────────────────────
                  _SectionLabel(
                    label: 'ATTRIBUTES',
                    color: AppColors.textSecondary,
                  ).animate().fadeIn(duration: 400.ms, delay: 500.ms),

                  const SizedBox(height: 12),

                  GridView.count(
                    crossAxisCount: 2,
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    crossAxisSpacing: 12,
                    mainAxisSpacing: 12,
                    childAspectRatio: 1.45,
                    children: [
                      SupportAttributeCard(
                        title: 'Career',
                        rpgLabel: 'Income Engine',
                        emoji: '💼',
                        color: AppColors.career,
                        xp: stats.careerXp,
                        route: '/career',
                        index: 0,
                      ),
                      SupportAttributeCard(
                        title: 'Knowledge',
                        rpgLabel: 'Skill Power',
                        emoji: '📚',
                        color: AppColors.knowledge,
                        xp: stats.knowledgeXp,
                        route: '/knowledge',
                        index: 1,
                      ),
                      SupportAttributeCard(
                        title: 'Habit',
                        rpgLabel: 'Discipline',
                        emoji: '🔥',
                        color: AppColors.habit,
                        xp: stats.habitXp,
                        route: '/habit',
                        index: 2,
                      ),
                      SupportAttributeCard(
                        title: 'Health',
                        rpgLabel: 'Energy',
                        emoji: '💪',
                        color: AppColors.health,
                        xp: stats.healthXp,
                        route: '/health',
                        index: 3,
                      ),
                    ],
                  ),

                  const SizedBox(height: 28),

                  // ── Daily Financial Todos + Motivation ─────────────────
                  DailyFinancialTodos(
                    todos: _todos,
                    onComplete: _completeTodo,
                    onDelete: _deleteTodo,
                    onAddCustom: _addCustomTodo,
                  ),

                  const SizedBox(height: 20),
                ]),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── Net Worth Quick Chip ──────────────────────────────────────────────────────

class _NetWorthChip extends StatelessWidget {
  final double amountIdr;
  final VoidCallback onEdit;

  const _NetWorthChip({
    required this.amountIdr,
    required this.onEdit,
  });

  @override
  Widget build(BuildContext context) {
    final mlProgress = FinancialRankCalculator.calculate(amountIdr);
    final mlRank = mlProgress.rank;
    // Always show IDR; USD is already shown in FinancialRankCard
    final amountStr = FinancialRankCalculator.formatIdrFull(amountIdr);

    return GestureDetector(
      onTap: onEdit,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
        decoration: BoxDecoration(
          color: mlRank.primaryColor.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: mlRank.primaryColor.withValues(alpha: 0.3)),
        ),
        child: Row(
          children: [
            Icon(Icons.account_balance_wallet_rounded,
                color: mlRank.primaryColor, size: 16),
            const SizedBox(width: 8),
            Text(
              'Net Worth: $amountStr',
              style: TextStyle(
                color: mlRank.primaryColor,
                fontSize: 13,
                fontWeight: FontWeight.w700,
              ),
            ),
            const Spacer(),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: mlRank.primaryColor.withValues(alpha: 0.15),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                  Icon(Icons.edit_rounded, color: mlRank.primaryColor, size: 10),
                  const SizedBox(width: 4),
                  Text(
                    'Edit',
                    style: TextStyle(
                      color: mlRank.primaryColor,
                      fontSize: 10,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── Section Label ─────────────────────────────────────────────────────────────

class _SectionLabel extends StatelessWidget {
  final String label;
  final Color color;

  const _SectionLabel({required this.label, required this.color});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Container(
          width: 3,
          height: 14,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: 10),
        Text(
          label,
          style: TextStyle(
            color: color,
            fontSize: 11,
            fontWeight: FontWeight.w800,
            letterSpacing: 2.5,
          ),
        ),
      ],
    );
  }
}
